Vs/scanner parser
Howon/Oscar pull request #16
Opened 2016-11-01 12:27 UTC by xvladus1

Moved scanner/parser changes from the AST PR here.

2016-11-02 02:47 UTC, Howon commented on src/parser.mly
>    | stmt_iter                                         { $1 }
Line 190 and 210's white spaces don't match but looks good to me

2016-11-06 20:15 UTC, xvladus1 commented on src/parser.mly
>    | stmt_iter                                         { $1 }
I think these should be fixed now.

2016-11-06 22:04 UTC, jibben requested changes

2016-11-06 22:04 UTC, jibbenHillen commented on src/parser.mly
> +  | LITERAL                                         { Int_Lit($1) }
Shouldn't this token by INT_LIT

2016-11-06 22:53 UTC, jibben approved these changes

2016-11-06 22:54 UTC, merged